title: "Amlan Das"
email: "contact@amlandas.in"
description: "CV and blogs by Amlan Das"
baseurl: ""
url: "https://AmlanDas1998.github.io"
repository: "AmlanDas1998/amlandas.in"

# Theme settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Navigation (Navbar)
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "CV"
    url: "/cv/"
